name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install package
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'dis/'
          dest: 'lengyu@35.220.216.177:/home/lengyu/tcloud'

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
